import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "../../dist/styles.css";
import "../../dist/compliance.css";
import "./react.css";

const EMPTY = { active_mode: null, models: {} };
const readyRuns = (catalog) => Object.entries(catalog?.models || {}).filter(([, run]) => run?.status === "ready").sort(([, a], [, b]) => String(b.completed_at || "").localeCompare(String(a.completed_at || "")));
const viewer = (id) => `textured_viewer.html${id ? `?mode=${encodeURIComponent(id)}` : ""}`;
const compact = (value) => Number.isFinite(Number(value)) ? Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 1 }).format(Number(value)) : "—";

function Header({ page }) { return <header className="topbar"><a className="brand" href="index.html"><span className="brand-orbit"><i /><i /><i /></span><span><b>EkaDrishti</b><small>Spatial Intelligence Lab</small></span></a><nav><a className={page === "build" ? "active" : ""} href="index.html">Build</a><a className={page === "library" ? "active" : ""} href="library.html">Library</a></nav><span className="system-status"><i /> LOCAL ENGINE ONLINE</span></header>; }

function MissionForm({ status, onProcess, profile, setProfile, video, telemetry, setVideo, setTelemetry, sending }) { const running = status.status === "running" || status.status === "cancelling"; return <aside className="mission-form"><p className="kicker">NEW RECONSTRUCTION / 01</p><h1>Build a model.</h1><p className="form-intro">Choose the source files from one DJI flight. The viewer will update when your local build is ready.</p><label className="mode-select">QUALITY PROFILE<select value={profile} onChange={(event) => setProfile(event.target.value)}><option value="precision">Precision · high detail</option><option value="rapid">Rapid · first look</option></select></label><div className="file-picks"><label htmlFor="mission-video"><span>01 / VIDEO</span><b>{video?.name || "Add flight video"}</b><small>{video ? "Selected · click to replace" : "DJI MP4 or MOV"}</small><input id="mission-video" type="file" accept="video/mp4,video/quicktime,.mp4,.mov" hidden onChange={(event) => setVideo(event.target.files?.[0] || null)} /></label><label htmlFor="mission-telemetry"><span>02 / TELEMETRY</span><b>{telemetry?.name || "Add telemetry"}</b><small>{telemetry ? "Selected · click to replace" : "Matching DJI SRT"}</small><input id="mission-telemetry" type="file" accept=".srt,text/plain" hidden onChange={(event) => setTelemetry(event.target.files?.[0] || null)} /></label></div>{running && <div className="processing"><i /><span><b>{status.stage || "Building local model"}</b><small>Processing is continuing on this computer.</small></span></div>}<button type="button" className="launch" onClick={onProcess} disabled={sending || running}>{running ? "BUILD IN PROGRESS" : "START 3D BUILD"}<span>→</span></button><p className="panel-foot">Every successful model is saved to the local library as a separate PLY file.</p></aside>; }

function BuildPage() { const [catalog, setCatalog] = useState(EMPTY); const [profile, setProfile] = useState("precision"); const [video, setVideo] = useState(null); const [telemetry, setTelemetry] = useState(null); const [status, setStatus] = useState({ status: "idle" }); const [notice, setNotice] = useState(""); const [sending, setSending] = useState(false); const load = async () => { try { const response = await fetch("/api/models", { cache: "no-store" }); if (response.ok) setCatalog(await response.json()); } catch {} }; const check = async () => { try { const response = await fetch("/api/status", { cache: "no-store" }); if (!response.ok) return; const data = await response.json(); setStatus(data); if (data.status === "complete") { setNotice("Your model is ready and saved in the Library."); load(); } if (data.status === "failed") setNotice(`Processing stopped: ${data.message || "Please check the local dashboard."}`); } catch {} }; useEffect(() => { load(); check(); }, []); useEffect(() => { if (status.status !== "running" && status.status !== "cancelling") return; const timer = setInterval(check, 2000); return () => clearInterval(timer); }, [status.status]); const build = async () => { if (!video || !telemetry) { setNotice("Add Video and Telemetry data to make a 3d model"); return; } setSending(true); setNotice(""); const form = new FormData(); form.append("video", video); form.append("telemetry", telemetry); form.append("profile", profile); try { const response = await fetch("/api/process", { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setStatus(data); } catch (error) { setNotice(error.message || "Could not start this mission."); } finally { setSending(false); } }; const requested = new URLSearchParams(location.search).get("model"); const id = requested && catalog.models?.[requested] ? requested : (catalog.active_mode && catalog.models?.[catalog.active_mode] ? catalog.active_mode : readyRuns(catalog)[0]?.[0]); return <main className="app-shell"><Header page="build" /><section className="build-layout"><MissionForm {...{ status, onProcess: build, profile, setProfile, video, telemetry, setVideo, setTelemetry, sending }} /><section className="viewer-stage"><div className="viewer-stage-head"><span className="kicker">LIVE 3D WORKSPACE</span><span>{id ? "MODEL LOADED" : "AWAITING INPUT"}</span></div><iframe title="Interactive 3D model viewer" src={viewer(id)} /></section></section>{notice && <div className="notice">{notice}<button onClick={() => setNotice("")} aria-label="Dismiss">×</button></div>}</main>; }

function LibraryPage() { const [catalog, setCatalog] = useState(EMPTY); useEffect(() => { fetch("/api/models", { cache: "no-store" }).then((response) => response.ok ? response.json() : EMPTY).then(setCatalog).catch(() => setCatalog(EMPTY)); }, []); const runs = readyRuns(catalog); return <main className="app-shell"><Header page="library" /><section className="library-page"><div className="library-heading"><p className="kicker">LOCAL MODEL ARCHIVE</p><h1>Every place,<br /><em>kept close.</em></h1><p>Select a completed mission to return to its saved PLY model. Each build is stored separately on this computer.</p></div><div className="library-list">{runs.length ? runs.map(([id, run], index) => <a className="run-card" key={id} href={`index.html?model=${encodeURIComponent(id)}`}><span className="run-index">{String(index + 1).padStart(2, "0")}</span><span className="run-copy"><b>{run.mission?.name || run.label || "Untitled mission"}</b><small>{run.label || "3D reconstruction"} · {run.completed_at ? new Date(run.completed_at).toLocaleDateString(undefined, { day: "2-digit", month: "short", year: "numeric" }) : "Saved locally"}</small></span><span className="run-meta">{compact(run.mission?.triangles || run.triangles)} faces<br /><i>OPEN ↗</i></span></a>) : <div className="empty-library"><span>◇</span><b>No saved models yet</b><small>Add Video and Telemetry data to make a 3d model.</small></div>}</div></section></main>; }

createRoot(document.getElementById("root")).render(location.pathname.endsWith("library.html") ? <LibraryPage /> : <BuildPage />);
